// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-ZtAG1zrW6LdO4x3izBLf6DzFcuOIXg',
    appId: '1:469103383148:web:0383ef1715a94011763e49',
    messagingSenderId: '469103383148',
    projectId: 'notely-e7d5f',
    authDomain: 'notely-e7d5f.firebaseapp.com',
    storageBucket: 'notely-e7d5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY8PMIxh15-Kmko_ddPT_10vf_tA2MYU0',
    appId: '1:469103383148:android:0003888a65311de3763e49',
    messagingSenderId: '469103383148',
    projectId: 'notely-e7d5f',
    storageBucket: 'notely-e7d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp6ycuy6ShF78zEh8gHgSCzAcH54WrCj0',
    appId: '1:469103383148:ios:0b8186297b6b6f98763e49',
    messagingSenderId: '469103383148',
    projectId: 'notely-e7d5f',
    storageBucket: 'notely-e7d5f.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp6ycuy6ShF78zEh8gHgSCzAcH54WrCj0',
    appId: '1:469103383148:ios:0b8186297b6b6f98763e49',
    messagingSenderId: '469103383148',
    projectId: 'notely-e7d5f',
    storageBucket: 'notely-e7d5f.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2-ZtAG1zrW6LdO4x3izBLf6DzFcuOIXg',
    appId: '1:469103383148:web:43ddc797530f06e8763e49',
    messagingSenderId: '469103383148',
    projectId: 'notely-e7d5f',
    authDomain: 'notely-e7d5f.firebaseapp.com',
    storageBucket: 'notely-e7d5f.firebasestorage.app',
  );
}
